### PR TITLE
feature: defined interfaces

### PR DESCRIPTION
**Pull request by Redi22**

### CODE REVIEW

**Review by miruts — CHANGES_REQUESTED** [review]
For naming interfaces lets use title case or pascal case i.e. ArticleInterface, to signify that its an interface we can prepend `I` to the interface name i.e. (IArticleInterface). update the other interfaces using the same convention. Rest, its good to go, except that I've pushed eslint and prettier configs to master, pull the changes and use prettier + eslint to check coding conventions and reformating of the code. (need to install VS code extentions for Eslint and Prettier) also don't forget `npm i` after pulling changes.

**Review by GedionT — DISMISSED** [review]
👍🏼 This LGTM! I will create a sample model for everyone to follow using one of the interfaces.

**Comment by Redi22** [comment]
> For naming interfaces lets use title case or pascal case i.e. ArticleInterface, to signify that its an interface we can prepend `I` to the interface name i.e. (IArticleInterface). update the other interfaces using the same convention. Rest, its good to go, except that I've pushed eslint and prettier configs to master, pull the changes and use prettier + eslint to check coding conventions and reformating of the code. (need to install VS code extentions for Eslint and Prettier) also don't forget `npm i` after pulling changes.

made the changes @miruts, give it a look.

**Review by GedionT — APPROVED** [review]

**Review by miruts — APPROVED** [review]
I will apply reformating based on rules on master after merging

**Pull request merged**
