### PR TITLE
Feat: added user model

### PR DESCRIPTION
**Pull request by ibsa21**

### CODE REVIEW

**Review by wubeZ — APPROVED** [review]
LGTM!

**Review by Redi22 — COMMENTED** [review]
Maybe we can make the required field consistent and keep it "true" or leave it.

**Review by miruts — COMMENTED** [review]
leaving some comments for future PRs
-consistent naming convention, i.e IUserInterface in the import alias instead of IuserInterface,
-remove unused imports
-prettier format
*tag commits* as [starter-project-g33] so that we know which pr's are g33's i.e "[starter-project-g33] Implement user model"

**Review by GedionT — APPROVED** [review]
added some more details and merged 👍🏼

**Pull request merged**
